meta_product_name: "Le Voyage"
meta_title: "Le Voyage | Alumni"
meta_description: "The Le Wagon alumni community"
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
